name: Regression Test

on:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew regression
        
    env:
     CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_REPORT }}
